services:
  patient-service-db:
    image: postgres:latest
    container_name: patient-service-db
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: admin_user
      POSTGRES_DB: db
    ports:
      - "5000:5432"
    volumes:
      - ./volumes/patient-service-db:/var/lib/postgresql/data
    networks:
      - internal

  patient-service:
    image: patient-service:latest
    build: .
    container_name: patient-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://patient-service-db:5432/db
      SPRING_DATASOURCE_USERNAME: admin_user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_SQL_INIT_MODE: always
      BILLING_SERVICE_ADDRESS: billing-service
      BILLING_SERVICE_GRPC_PORT: 9001
    ports:
      - "4000:4000"
    networks:
      - internal

volumes:
  postgres_data:

networks:
  internal:
    driver: bridge