### Creates a new patient entity
POST http://lb-565a4450.elb.localhost.localstack.cloud:4004/api/patients
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Caio H. Portella",
  "email": "portella@chp.com",
  "address": "666 Acacia Avenue",
  "dateOfBirth": "2001-06-02",
  "registeredDate": "2025-05-28"
}
###